### ISSUE TITLE
Add default base images in xp.conf

### ISSUE THREAD

**Issue by msimonin** [capi5k/capi5k-openstack#10]
The current installation is bootstraped with a custom image whose references (name / location) is hardcoded somewhere in the code (`Capfile`). It could be easy to use the xp.conf provide a list images to add to glance upon bootstraping.

Maybe something like : 

``` yaml
images:
  - short   :"ubuntu13.10":
    location: "http://public.rennes.grid5000.fr/~msimonin/ubuntu-13.10-server-clouding-amd64-disk1.img"
    name    : "ubuntu-13.10-server-clouding-amd64-disk1.img"
 - short   :"centos":
    location: "..."
    name    : "..."
```
